project_id: '310610'
api_token_env: CROWDIN_PERSONAL_TOKEN
preserve_hierarchy: true

files:
  - source: /docs/EN/**/*.md
    translation: /docs/CROWDIN/%two_letters_code%/%original_path%/%original_file_name%
  - source: /docs/EN/**/*.rst
    translation: /docs/CROWDIN/%two_letters_code%/%original_path%/%original_file_name%
  - source: /docs/EN/images/**/*
    translation: /docs/CROWDIN/%two_letters_code%/images/%original_path%/%original_file_name%
