name: Automatic Start RTD Build after merge of PR in branch rework-project

on:
  push:
    branches:
      - rework-project
      
  workflow_dispatch:

jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      uses: wei/curl@v1
      with:
        args: -X POST -d "branches=${{ steps.extract_branch.outputs.branch }}" -d "token=${{ secrets.RTD_WEBHOOK_KEY_EN }}" https://readthedocs.org/api/v2/webhook/androidaps/145178/
