name: Update translations

on:
  push:
    branches:
      - master
  schedule:
    - cron: '7 0 * * *' # every day at 00:07 UTC
  workflow_dispatch:

env:
  CROWDIN_PROJECT_ID: '310610'

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest
    if: github.repository == 'openaps/AndroidAPSdocs'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: crowdin action
        uses: crowdin/github-action@v1
        with:
          upload_sources: true
          upload_translations: false
          download_translations: true
          localization_branch_name: l10n_translations
          create_pull_request: true
          pull_request_title: 'New translations'
          pull_request_body: 'New translations'
          pull_request_base_branch_name: 'main'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}